---
- name: Restart registry container
  community.docker.docker_container:
    name: registry
    state: started
    restart: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
