---
- name: Configure ZSH
  block:
    - name: "Step 1. Install ZSH"
      ansible.builtin.apt:
        name:
          - zsh
        state: present
      become: true

    - name: "Step 2. Install oh-my-zsh"
      ansible.builtin.shell:
        cmd: |-
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: "/home/{{ ssh_user }}/.oh-my-zsh"
      become: false

    - name: "Step 3. Install ZSH plugins"
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/home/{{ ssh_user }}/{{ item.dest }}"
      loop:
        - repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
          dest: '.oh-my-zsh/custom/plugins/zsh-autosuggestions'
        - repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
          dest: '.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'
      become: false

    - name: "Step 4. Configure ~/.zshrc"
      ansible.builtin.template:
        src: 02-zshrc.j2
        dest: "/home/{{ ssh_user }}/.zshrc"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
      become: false

    - name: "Step 5. Set ZSH as default shell"
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        shell: /usr/bin/zsh
      become: true
