---
- name: "Section A: Run OS prerequisites for Redis"
  block:
    - name: "Step A1. Check if swap is active"
      ansible.builtin.command: swapon --show
      register: swapon_check
      changed_when: false
      failed_when: false

    - name: "Step A2. Disable swap if it is active"
      ansible.builtin.command: swapoff -a
      when: swapon_check.stdout != ""
      changed_when: true

    - name: "Step A3. Comment out swap entries in /etc/fstab to persist change"
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'
