---
- name: "Section A: Ensure Snapd service is ready"
  become: true
  block:
    - name: "Step A1. Install prerequisites for Snap"
      ansible.builtin.apt:
        name:
          - snapd
        state: present
        update_cache: true

    - name: "Step A2. Ensure snapd service is started and enabled"
      ansible.builtin.systemd:
        name: snapd
        state: started
        enabled: true

    - name: "Step A3. Wait for snapd to become fully ready"
      ansible.builtin.command:
        cmd: "snap wait system seed.loaded"
      changed_when: false
      retries: 10
      delay: 5

- name: "Section B: Install MicroK8s and create aliases"
  become: true
  block:
    - name: "Step B1. Install MicroK8s via Snap"
      community.general.snap:
        name: microk8s
        classic: true
        channel: "1.32/stable"

    - name: "Step B2. Wait for MicroK8s to be ready"
      ansible.builtin.command:
        cmd: "microk8s status --wait-ready"
      changed_when: false

    - name: "Step B3. Alias microk8s.kubectl to kubectl"
      ansible.builtin.command:
        cmd: "snap alias microk8s.kubectl kubectl"
      args:
        creates: /snap/bin/kubectl
      changed_when: true

    - name: "Step B4. Alias microk8s.helm3 to helm"
      ansible.builtin.command:
        cmd: "snap alias microk8s.helm3 helm"
      args:
        creates: /snap/bin/helm
      changed_when: true

- name: "Section C: Add SSH user to the 'microk8s' group for basic access"
  become: true
  block:
    - name: "Step C1. Add user to the 'microk8s' group"
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: microk8s
        append: true
