---
- name: "--- Start processing device: {{ current_device }} ---"
  ansible.builtin.debug:
    msg: "Starting attempt for device {{ current_device }}"

- name: "Attempting to mount {{ current_device }}"
  ansible.posix.mount:
    path: /mnt/VBoxGuestAdditions
    src: "{{ current_device }}"
    fstype: iso9660
    opts: ro
    state: mounted
  register: mount_result
  ignore_errors: true

- name: "DEBUG: Mount attempt result for {{ current_device }}"
  ansible.builtin.debug:
    var: mount_result
    verbosity: 2 # Show all details

- name: Check for installer script on the mounted device
  when: mount_result is succeeded
  ansible.builtin.stat:
    path: /mnt/VBoxGuestAdditions/VBoxLinuxAdditions.run
  register: installer_script

- name: "DEBUG: Installer script check result for {{ current_device }}"
  when: mount_result is succeeded
  ansible.builtin.debug:
    var: installer_script
    verbosity: 2 # Show all details
  changed_when: false

- name: Install if the script is found
  when: installer_script.stat is defined and installer_script.stat.exists
  block:
    - name: "Running installation from device: {{ current_device }}"
      ansible.builtin.shell:
        cmd: "yes | /mnt/VBoxGuestAdditions/VBoxLinuxAdditions.run --nox11"
      register: installation_result
      ignore_errors: true
      changed_when: false

    - name: "DEBUG: Installation command output from {{ current_device }}"
      ansible.builtin.debug:
        var: installation_result
        verbosity: 2

    - name: "Unmount after installation attempt"
      ansible.posix.mount:
        path: /mnt/VBoxGuestAdditions
        state: absent

- name: Unmount if it was the wrong device
  when: (installer_script.stat is not defined or not installer_script.stat.exists) and mount_result is succeeded
  ansible.posix.mount:
    path: /mnt/VBoxGuestAdditions
    state: unmounted
