---
- name: Load kernel modules
  ansible.builtin.command: modprobe {{ item }}
  listen: "Load kernel modules"
  loop:
    - overlay
    - br_netfilter
  changed_when: true

- name: Apply sysctl settings
  listen: "Apply sysctl settings"
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Enable and start crio service
  listen: "Enable and start crio service"
  ansible.builtin.systemd:
    name: crio
    enabled: true
    state: started
    daemon_reload: true

- name: "Reboot the machine"
  listen: "Reboot the machine"
  ansible.builtin.reboot:
    msg: "Rebooting machine to finalize open-vm-tools installation."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
