---
- name: "Section A: Prepare worker node for joining"
  block:
    - name: "Step 1. Reset any previous kubeadm configuration"
      ansible.builtin.command: kubeadm reset -f
      changed_when: true

    - name: "Step 2. Ensure kubelet service is enabled and started"
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true

- name: "Section B: Join this worker node to the cluster"
  block:
    - name: "Step 1. Execute the worker join command"
      # 關鍵步驟：使用 hostvars 從 master-00 取得 "worker" 專用的 join 指令
      ansible.builtin.command: "{{ hostvars[groups['master'][0]]['kubeadm_join_command_worker'] }}"
      args:
        # 同樣使用 kubelet.conf 作為冪等性判斷
        creates: /etc/kubernetes/kubelet.conf
      register: kubeadm_join_result

    - name: "Step 2. Fail if kubeadm join command failed"
      ansible.builtin.fail:
        msg: |
          kubeadm join failed on {{ inventory_hostname }}.
          STDOUT: {{ kubeadm_join_result.stdout | default('N/A') }}
          STDERR: {{ kubeadm_join_result.stderr | default('N/A') }}
      when: kubeadm_join_result.rc is defined and kubeadm_join_result.rc != 0 \
