---
- name: "Section. Block for VMware Workstation prerequisites"
  block:
    - name: "Step 1. Action: Install open-vm-tools from Ubuntu repository"
      ansible.builtin.apt:
        name:
          - open-vm-tools
        state: present
        update_cache: true
      notify:
        - Reboot the machine

    - name: "Step 2. Meta: Force all notified handlers to run now"
      ansible.builtin.meta: flush_handlers

    - name: "Step 3. Verify: Get list of loaded kernel modules"
      ansible.builtin.command: lsmod
      register: lsmod_result
      changed_when: false

    - name: "Step 4. Verify: Assert that VMware modules are loaded"
      ansible.builtin.assert:
        that:
          - "'vmw_balloon' in lsmod_result.stdout"
          - "'e1000' in lsmod_result.stdout"
        fail_msg: "Verification failed: VMware kernel modules are not loaded."
        success_msg: "Verification successful: VMware kernel modules are loaded."
