---
- name: "Section A: Configure Docker Registry"
  block:
    - name: "Step A1. Create directory for registry config and data"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /data/registry
        - /etc/docker/registry

    - name: "Step A2. Template out the registry-config.yml for local binding"
      ansible.builtin.template:
        src: registry-config.yml.j2
        dest: /etc/docker/registry/config.yml
        mode: "0644"
      vars:
        nginx_listen_ip: "{{ ansible_facts['ens3']['ipv4']['address'] }}"

    - name: "Step A3. Ensure Docker Registry container is running correctly on localhost"
      community.docker.docker_container:
        name: registry
        image: registry:2
        state: started
        restart_policy: always
        ports:
          - "127.0.0.1:5000:5000" # Bind to localhost ONLY
        volumes:
          - /data/registry:/var/lib/registry
          - /etc/docker/registry/config.yml:/etc/docker/registry/config.yml:ro

- name: "Section B: Configure Nginx as a Reverse Proxy"
  block:
    - name: "Step B1. Install Nginx"
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: "Step B2. Template out the Nginx configuration"
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/registry
        mode: "0644"
      vars:
        nginx_listen_ip: "{{ ansible_facts['ens3']['ipv4']['address'] }}"
      notify: Restart nginx

    - name: "Step B3. Enable the Nginx site for the registry"
      ansible.builtin.file:
        src: /etc/nginx/sites-available/registry
        dest: /etc/nginx/sites-enabled/registry
        state: link
      notify: Restart nginx

    - name: "Step B4. Remove default Nginx site"
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

    - name: "Step B5. Ensure Nginx service is started and enabled"
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
