---
- name: Create Calico operator flag file
  listen: "Create Calico operator flag file"
  ansible.builtin.file:
    path: /etc/kubernetes/calico-operator-installed.flag
    state: touch
    mode: '0600'
