---
- name: "Play 1: Provision MicroK8s base image"
  hosts: "10-registry-base"
  become: true
  roles:
    - 04-base-microk8s

- name: "Play 2: Provision Kubernetes base image"
  hosts: "20-k8s-base"
  become: true
  roles:
    - 02-base-kubernetes

- name: "Play 3: Final Permission Check and Clean up"
  hosts: "all"
  become: true
  roles:
    - 09-image-finalization
