---
- name: "Play: Provision Kubernetes (Kubeadm) base image"
  hosts: "02-base-kubeadm"
  become: true
  roles:
    - 02-base-kubeadm

- name: "Play: Provision MicroK8s base image"
  hosts: "03-base-microk8s"
  become: true
  roles:
    - 03-base-microk8s

- name: "Play: Final Permission Check and Clean up"
  hosts: "all"
  become: true
  roles:
    - 09-image-finalization
