---
- name: Section A. Run OS prerequisites setup
  block:
    - name: "Step 1. Action: Add Universe and Multiverse repositories"
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse"
        state: present
        filename: 'ubuntu-with-community'
        update_cache: true

    - name: "Step 2. Action: Install build dependencies"
      ansible.builtin.apt:
        name:
          - build-essential
          - dkms
          - "linux-headers-{{ ansible_kernel }}"
          - perl
          - libelf-dev
        state: present
        update_cache: true

    - name: "Step 3. Action: Install open-vm-tools from Ubuntu repository"
      ansible.builtin.apt:
        name:
          - open-vm-tools
        state: present
        update_cache: true
      notify:
        - Reboot the machine

    - name: "Step 4. Meta: Force all notified handlers to run now"
      ansible.builtin.meta: flush_handlers

    - name: "Step 5.a Verify: Get list of loaded kernel modules"
      ansible.builtin.command: lsmod
      register: lsmod_result
      changed_when: false

    - name: "Step 5.b Verify: Assert that VMware modules are loaded"
      ansible.builtin.assert:
        that:
          - "'vmw_balloon' in lsmod_result.stdout"
          - "'e1000' in lsmod_result.stdout"
        fail_msg: "Verification failed: VMware kernel modules are not loaded."
        success_msg: "Verification successful: VMware kernel modules are loaded."

    - name: "Step 6. Harden: Ensure sshd service is enabled and starts on boot"
      ansible.builtin.systemd:
        name: ssh
        state: started
        enabled: true
