---
- name: Section A. Run OS prerequisites setup
  ansible.builtin.include_tasks: 01-prerequisites-os.yml

- name: Section B. Run Kubernetes prerequisites setup
  ansible.builtin.include_tasks: 02-prerequisites-k8s.yml

- name: Section C. Install and Configure container runtime
  ansible.builtin.include_tasks: 03-container-runtime.yml

- name: Section D. Install Kubernetes components
  ansible.builtin.include_tasks: 04-kube-components.yml

- name: Section E. Finalize image and clean up
  ansible.builtin.include_tasks: 05-finalization.yml
