---
- name: "Section B: Install Patroni Runtime Dependencies"
  become: true
  block:
    - name: "Step B1. Install Python environment and build tools"
      ansible.builtin.apt:
        name:
          - python3-venv
          - python3-pip
          - libpq-dev
          - build-essential
        state: present
