---
- name: Section B. Run Kubernetes prerequisites setup
  block:
    - name: "Step 1. Update cache and install basic packages"
      ansible.builtin.apt:
        name:
          - wget
          - git
          - curl
          - vim
          - jq
          - snapd
          - tree
          - gh
          - htop
          - net-tools
        state: present
        update_cache: true
        cache_valid_time: 3600
      no_log: true

    - name: "Step 2. Enable bridge traffic modules"
      ansible.builtin.template:
        src: B-k8s_modules.j2
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"
      notify: Load kernel modules

    - name: "Step 3. Set sysctl parameters"
      ansible.builtin.template:
        src: B-k8s_sysctl.conf.j2
        dest: /etc/sysctl.d/k8s.conf
        mode: "0644"
      notify: Apply sysctl settings

    - name: "Step 4. Check if swap is active"
      ansible.builtin.command: swapon --show
      register: swapon_check
      changed_when: false
      failed_when: false

    - name: "Step 5. Disable swap if it is active"
      ansible.builtin.command: swapoff -a
      when: swapon_check.stdout != ""
      changed_when: true

    - name: "Step 6. Comment out swap entries in /etc/fstab"
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'
