---
- name: "Step 1. Install pip for Python"
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: "Step 2. Install Docker SDK for Python"
  ansible.builtin.pip:
    name: docker
    state: present
    extra_args: "--break-system-packages"

- name: "Step 3. Create a directory for registry data"
  ansible.builtin.file:
    path: /data/registry
    state: directory
    mode: "0755"

- name: "Step 4. Start the Docker Registry container"
  community.docker.docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    volumes:
      - /data/registry:/var/lib/registry
