---
- name: Section A. Initialize Kubernetes Master Node
  block:
    - name: "Step 1. Create kubelet configuration for CRI-O"
      ansible.builtin.copy:
        dest: "/etc/default/kubelet"
        content: "KUBELET_EXTRA_ARGS=--container-runtime-endpoint=unix:///var/run/crio/crio.sock"
        mode: '0644'

    - name: "Step 2. Flush all pending handlers NOW"
      ansible.builtin.meta: flush_handlers

    - name: "Step 3. Initialize kubeadm"
      ansible.builtin.command: >-
        kubeadm init
        --apiserver-advertise-address={{ advertise_ip }}
        --pod-network-cidr=10.244.0.0/16
        --node-name={{ inventory_hostname }}
        --ignore-preflight-errors=Swap
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      changed_when: "'Your Kubernetes control-plane has initialized successfully!' in kubeadm_init.stdout"
