---
- name: Section B. Set up kubeconfig for users
  block:
    - name: "Step 1. Create .kube directory for the root user"
      ansible.builtin.file:
        path: "/root/.kube"
        state: directory
        mode: '0755'

    - name: "Step 2. Copy admin.conf to root's kube config"
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/root/.kube/config"
        remote_src: true
        mode: '0600'

    - name: "Step 3. Create .kube directory for the user"
      ansible.builtin.file:
        path: "/home/{{ ansible_ssh_user }}/.kube"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0755'

    - name: "Step 4. Copy admin.conf to user's kube config"
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_ssh_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0644'
