---
- name: Section A. Initialize Kubernetes master node
  ansible.builtin.include_tasks: 11-init-master.yml

- name: Section B. Set up kubeconfig for users
  ansible.builtin.include_tasks: 12-setup-kubeconfig.yml

- name: Section C. Install Container Network Interface (CNI)
  ansible.builtin.include_tasks: 13-install-cni.yml

- name: Section D. Generate and register the cluster join command
  ansible.builtin.include_tasks: 14-generate-join-command.yml
